services:
  java_app:
    container_name: java_app
    image: yh13431/java_app:1.0.0
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    env_file: ".env"
    depends_on:
      - java_db

  test_service:
    container_name: java_app_tests
    image: yh13431/java_app:1.0.0 
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: mvn test -Dtest='!*BackendApplicationTests' 
    env_file: ".env"
    depends_on:
      - java_db

  java_db:
    container_name: java_db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file: ".env"
    volumes:
      - pgdata:/var/lib/postgresql/data

  js_frontend:
    container_name: js_frontend
    image: yh13431/js_frontend:1.0.0
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000

volumes:
  pgdata: {}