name: backend_ci

on:
  push:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v6.5.0
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build backend
        run: cd backend && ./mvnw package

      - name: Build Docker image
        run: |
          docker build -t yh13431/java_app:1.0.0 ./backend

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u yh13431 --password-stdin

      - name: Push Docker image
        run: docker push yh13431/java_app:1.0.0