name: backend_ci

on:
  push:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List files in the backend directory
        run: ls -la ./backend

      - name: Make mvnw executable
        run: chmod +x ./backend/mvnw

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build backend JAR
        run: ./mvnw clean package -DskipTests
        working-directory: ./backend

      - name: List files in the backend target directory
        run: ls -la ./backend/target

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6.5.0
        with:
          context: ./backend
          push: true
          tags: user/app:latest
