name: Backend CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build Docker image
        run: |
          docker build -t yh13431/java_app:1.0.0 ./backend

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u yh13431 --password-stdin

      - name: Push Docker image
        run: docker push yh13431/java_app:1.0.0