name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build the Docker image
        run: |
          docker build . --file backend/Dockerfile --tag yh13431/java_app:latest

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: yh13431
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker tag my-image-name:$(date +%s) yh13431/java_app:latest
          docker push yh13431/java_app:latest

